#!/bin/bash
# script to make a new entry

# class name
if [[ $# -eq 0 ]]
then
    echo "Usage: $0 class [type]"
    exit
fi
CLASS=$1

# filename
TYPE=$2
if [[ $TYPE == "" ]]
then
    TYPE=lecture
fi
FILENAME="$CLASS"-"$TYPE"-$(date +%Y%m%d).md

hugo new --editor vim "$CLASS"/"$FILENAME"
